# Generated by Django 5.1.6 on 2025-02-28 05:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('subjects', '__first__'),
        ('tags', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('video_url', models.URLField(blank=True)),
                ('permalink', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.TextField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', models.URLField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='subjects.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='lessons', to='tags.tag')),
            ],
        ),
    ]
