# Generated by Django 5.1.6 on 2025-03-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoncompletion'),
        ('subjects', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='LessonSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('permalink', models.SlugField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='lessons.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='snapshot_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_completions', to='lessons.lessonsnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('user', 'lesson'), ('user', 'snapshot_lesson')},
        ),
    ]
