# Generated by Django 5.1.6 on 2025-03-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lessoncompletion_lesson_lessonsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsnapshot',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='created_by',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='og_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='og_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='og_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lessonsnapshot',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
