# Generated by Django 5.1.6 on 2025-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_lessonsnapshot_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsnapshot',
            name='title',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
