# Generated by Django 5.1.6 on 2025-03-15 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_coursesnapshot'),
        ('lessons', '0007_lessonsnapshot_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='lessons.lesson'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='snapshot_lesson',
        ),
        migrations.DeleteModel(
            name='LessonSnapshot',
        ),
    ]
