# Generated by Django 5.1.6 on 2025-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
