# Generated by Django 5.1.6 on 2025-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lesson_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='accent_color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='lesson',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Optional user-defined custom CSS for this lesson.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('dark', 'Dark')], default='modern', max_length=20),
        ),
    ]
