# Generated by Django 5.1.6 on 2025-05-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_lesson_accent_color_lesson_custom_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('accent_color', models.CharField(default='#3498db', max_length=7)),
                ('predefined_css', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='template_ref',
            field=models.ForeignKey(blank=True, help_text='Optionally choose a pre-defined template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.lessontemplate'),
        ),
    ]
