# Generated by Django 5.1.6 on 2025-05-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_lessontemplate_lesson_template_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='template_ref',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
        migrations.DeleteModel(
            name='LessonTemplate',
        ),
    ]
