# Generated by Django 5.1.6 on 2025-05-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_lessontemplate_lesson_accent_color_lesson_custom_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='template_ref',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
        migrations.DeleteModel(
            name='LessonTemplate',
        ),
    ]
