# Generated by Django 5.1.6 on 2025-11-20 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_selling_points_course_stripe_price_id_and_more'),
        ('lessons', '0018_lessontemplate_lesson_accent_color_lesson_custom_css_and_more'),
        ('subjects', '0001_initial'),
        ('tags', '0002_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Optional user‑defined JavaScript to execute only on this lesson page', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'position'], name='lessons_les_course__6bd811_idx'),
        ),
    ]
