# Generated by Django 5.1.6 on 2025-11-21 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_selling_points_course_stripe_price_id_and_more'),
        ('lessons', '0019_lesson_custom_js_lesson_is_premium_lesson_position_and_more'),
        ('subjects', '0001_initial'),
        ('tags', '0002_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='export_docx',
            field=models.FileField(blank=True, null=True, upload_to='lesson_exports/docx/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='export_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='export_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lesson_exports/pdf/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['permalink'], name='lessons_les_permali_f88b00_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_by', 'status', 'is_premium'], name='lessons_les_created_4085bd_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['updated_at'], name='lessons_les_updated_50d980_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['user', 'completed_at'], name='lessons_les_user_id_79b2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['lesson', 'completed_at'], name='lessons_les_lesson__df8ef8_idx'),
        ),
    ]
