# Generated by Django 5.1.6 on 2025-12-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_lesson_export_docx_lesson_export_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the user started this lesson', null=True),
        ),
    ]
