# Generated by Django 5.1.6 on 2025-02-28 05:21

import django.db.models.deletion
import django_ckeditor_5.fields
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('permalink', models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[posts.models.validate_permalink])),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters.', max_length=60)),
                ('seo_description', models.TextField(blank=True, help_text='Recommended: 50-160 characters.', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword for this post.', max_length=100)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content issues.')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, Twitter, etc.).', max_length=100)),
                ('og_description', models.TextField(blank=True, help_text='Short description for social media previews.', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Upload an image for social media previews (Open Graph image).', null=True, upload_to='post_og_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
