# Generated by Django 5.1.6 on 2025-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('tags', '0003_tag_description_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tags.tag'),
        ),
    ]
