# Generated by Django 5.1.6 on 2025-12-15 15:51

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_kind_048959_idx',
            old_name='assets_asset_kind_created_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_suggest_4ad31b_idx',
            old_name='assets_asset_name_kind_idx',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to=assets.models.asset_file_path),
        ),
    ]
