# Generated by Django 5.1.6 on 2025-02-28 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('permalink', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, help_text='Recommended: 50-60 characters.', max_length=60)),
                ('seo_description', models.TextField(blank=True, help_text='Recommended: 50-160 characters.', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword for this page.', max_length=100)),
                ('canonical_url', models.URLField(blank=True, help_text='URL to specify the canonical source.')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing.', max_length=100)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description for social sharing.', max_length=200)),
                ('og_image', models.URLField(blank=True, help_text='URL of the Open Graph image.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
