# Generated by Django 5.1.6 on 2025-12-11 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0002_interactive_multilingual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Student Learning Insight',
                'verbose_name_plural': '📊 Student Learning Insights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable teacher content generation globally')),
                ('default_language', models.CharField(default='en', help_text='Default language for generation (en, ja, es, fr, de, etc)', max_length=12)),
                ('default_output_format', models.CharField(choices=[('text', 'Text Only'), ('audio', 'Audio Only'), ('both', 'Text & Audio')], default='both', help_text='Default output: text only, audio only, or both', max_length=10)),
                ('default_llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('template', 'Template')], default='template', help_text='Default LLM for script generation (template, OpenAI, Gemini)', max_length=20)),
                ('openai_model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model name (gpt-4, gpt-4o-mini, gpt-3.5-turbo, etc)', max_length=50)),
                ('gemini_model', models.CharField(default='gemini-2.0-pro-exp', help_text='Google Gemini model name', max_length=50)),
                ('default_tts_provider', models.CharField(choices=[('elevenlabs', '🎵 ElevenLabs (Most Natural)'), ('google', '🎤 Google TTS (Standard Quality)'), ('google_chirp', '✨ Google Wavenet Premium (Highest Quality)'), ('gemini', '🎧 Google Standard (Fast & Good)'), ('openai', '🔊 OpenAI TTS (Consistent)'), ('polly', '🗣️ Amazon Polly (Multi-accent)'), ('none', '🚫 None (Text Only)')], default='elevenlabs', help_text='Default TTS provider (elevenlabs, google, openai, polly)', max_length=20)),
                ('tts_fallback_chain', models.JSONField(blank=True, default=list, help_text='Fallback order: ["elevenlabs", "google", "openai"]')),
                ('tts_speaking_rate', models.FloatField(default=1.0, help_text='TTS speaking rate (0.5=slow, 1.0=normal, 1.5=fast)')),
                ('tts_pitch', models.FloatField(default=0.0, help_text='TTS pitch adjustment (-20.0 to +20.0)')),
                ('tts_volume_gain', models.FloatField(default=0.0, help_text='TTS volume gain in dB (-16.0 to +16.0)')),
                ('voice_map_json', models.JSONField(blank=True, default=dict, help_text='Map of language codes to voice IDs/names: {"en": "voice-id", "ja": "voice-id"}')),
                ('script_word_limit_normal', models.PositiveIntegerField(default=700, help_text='Target word count for normal scripts (for audio ~6-8 min)')),
                ('script_word_limit_short', models.PositiveIntegerField(default=300, help_text="Target word count for short scripts (when notes say 'short')")),
                ('script_include_questions', models.BooleanField(default=True, help_text='Include Q&A format in generated scripts')),
                ('num_questions_per_script', models.PositiveIntegerField(default=3, help_text='Number of questions to include in interactive scripts')),
                ('include_motivational_quote', models.BooleanField(default=True, help_text='Include motivational quote at the end')),
                ('prompt_system_role', models.TextField(default='You are a warm, enthusiastic, and engaging teacher.', help_text='System role/personality for LLM generation')),
                ('prompt_script_intro', models.TextField(default='Create a conversational teacher script for a student who is learning.', help_text='Introduction instruction for script generation')),
                ('prompt_tone_guide', models.TextField(default='Use natural pauses, show genuine emotion, speak with warmth like chatting with a friend.', help_text='Tone guidance for generated content')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours to wait between generations for regular users')),
                ('test_user_cooldown_enabled', models.BooleanField(default=False, help_text='Apply cooldown to test users (Alex)')),
                ('max_generations_per_day', models.PositiveIntegerField(default=0, help_text='Max generations per day per user (0=unlimited)')),
                ('cost_per_generation', models.DecimalField(decimal_places=2, default=0.5, help_text='Credit cost per generation (0=free)', max_digits=8)),
                ('enable_credit_system', models.BooleanField(default=False, help_text='Require users to spend credits for generation')),
                ('support_bilingual', models.BooleanField(default=True, help_text='Allow bilingual content (e.g. EN + JA)')),
                ('bilingual_default_pair', models.CharField(default='en_ja', help_text='Default bilingual pair format: "en_ja", "en_es", etc', max_length=20)),
                ('bilingual_audio_stitch', models.BooleanField(default=True, help_text='Stitch bilingual audio into single MP3 (vs separate files)')),
                ('verbose_logging', models.BooleanField(default=True, help_text='Log detailed info about each generation')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug output (use carefully in production)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Podcast Defaults',
                'verbose_name_plural': 'Global Podcast Defaults',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Teachers, Students, Admins)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Group',
                'verbose_name_plural': 'Student Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable content generation for this category')),
                ('default_language', models.CharField(default='en', help_text='Default language for this category', max_length=12)),
                ('default_output_format', models.CharField(choices=[('text', 'Text Only'), ('audio', 'Audio Only'), ('both', 'Text & Audio')], default='both', help_text='Default output format for this category', max_length=10)),
                ('default_llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('template', 'Template')], default='template', help_text='Default LLM provider for this category', max_length=20)),
                ('openai_model', models.CharField(blank=True, default='gpt-4o-mini', help_text='OpenAI model for this category', max_length=50)),
                ('gemini_model', models.CharField(blank=True, default='gemini-2.0-pro-exp', help_text='Google Gemini model for this category', max_length=50)),
                ('claude_model', models.CharField(blank=True, default='claude-3-5-sonnet', help_text='Anthropic Claude model for this category', max_length=50)),
                ('template_model', models.CharField(blank=True, default='template', help_text='Template model for this category (no AI)', max_length=50)),
                ('default_tts_provider', models.CharField(choices=[('elevenlabs', '🎵 ElevenLabs (Most Natural)'), ('google', '🎤 Google TTS (Standard Quality)'), ('google_chirp', '✨ Google Wavenet Premium (Highest Quality)'), ('gemini', '🎧 Google Standard (Fast & Good)'), ('openai', '🔊 OpenAI TTS (Consistent)'), ('polly', '🗣️ Amazon Polly (Multi-accent)'), ('none', '🚫 None (Text Only)')], default='elevenlabs', help_text='Default TTS provider for this category', max_length=20)),
                ('tts_speaking_rate', models.FloatField(default=1.0, help_text='TTS speaking rate (0.5=slow, 1.0=normal, 1.5=fast)')),
                ('script_word_limit', models.PositiveIntegerField(default=700, help_text='Default word limit for scripts in this category')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours between generations (0=no limit)')),
                ('max_generations_per_day', models.PositiveIntegerField(default=5, help_text='Max generations per day (0=unlimited)')),
                ('cost_per_generation', models.DecimalField(decimal_places=2, default=0.5, help_text='Cost per podcast generation for this category', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Override',
                'verbose_name_plural': 'Category Overrides',
            },
        ),
        migrations.RenameIndex(
            model_name='dailypodcast',
            new_name='dailycast_d_user_id_1c0e53_idx',
            old_name='dailycast_user_date_idx',
        ),
        migrations.RemoveField(
            model_name='dailypodcast',
            name='language',
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='can_request_again_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this user can request next podcast (24h cooldown)', null=True),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='category',
            field=models.CharField(blank=True, help_text='Category/Subject of the request', max_length=100),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='month_range',
            field=models.CharField(choices=[('current', 'Current Month'), ('last_3', 'Last 3 Months'), ('last_6', 'Last 6 Months'), ('last_12', 'Last Year (12 Months)'), ('all', 'All Time')], default='current', help_text='Time period for content included in podcast', max_length=20),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes/instructions'),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='profession',
            field=models.CharField(blank=True, help_text='Professional context', max_length=100),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='reply_size',
            field=models.CharField(choices=[('short', 'Short (2-3 minutes)'), ('medium', 'Medium (4-5 minutes)'), ('long', 'Long (6-8 minutes)'), ('detailed', 'Detailed (10+ minutes)')], default='medium', help_text='Duration/depth of podcast response', max_length=20),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full request payload including selected items'),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Who triggered this generation (for auditing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='requested_by_user',
            field=models.BooleanField(db_index=True, default=False, help_text='True = user/staff clicked button, False = system/task generated'),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='topic',
            field=models.CharField(blank=True, help_text='Specific topic requested', max_length=255),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='user_request_type',
            field=models.CharField(choices=[('user', 'User Self-Request'), ('admin_dashboard', 'Admin Dashboard Button'), ('api', 'API Endpoint'), ('celery_task', 'Scheduled Task'), ('cli', 'CLI Command')], default='user', help_text='How was this podcast requested?', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailypodcast',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Primary language audio', null=True, upload_to='podcasts/'),
        ),
        migrations.AlterField(
            model_name='dailypodcast',
            name='tts_provider',
            field=models.CharField(choices=[('elevenlabs', '🎵 ElevenLabs (Most Natural)'), ('google', '🎤 Google TTS (Standard Quality)'), ('google_chirp', '✨ Google Wavenet Premium (Highest Quality)'), ('gemini', '🎧 Google Standard (Fast & Good)'), ('openai', '🔊 OpenAI TTS (Consistent)'), ('polly', '🗣️ Amazon Polly (Multi-accent)'), ('none', '🚫 None (Text Only)')], default='polly', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dailypodcast',
            index=models.Index(fields=['status', '-created_at'], name='dailycast_d_status_58aedd_idx'),
        ),
        migrations.AddField(
            model_name='teachercontentconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='users',
            field=models.ManyToManyField(help_text='Users in this category', related_name='podcast_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercategoryconfig',
            name='category',
            field=models.OneToOneField(help_text='User category this config applies to', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='dailycast.usercategory'),
        ),
    ]
