# Generated by Django 5.1.6 on 2025-12-07 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0002_interactive_multilingual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailypodcast',
            new_name='dailycast_d_user_id_1c0e53_idx',
            old_name='dailycast_user_date_idx',
        ),
        migrations.RemoveField(
            model_name='dailypodcast',
            name='language',
        ),
        migrations.AlterField(
            model_name='dailypodcast',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Primary language audio', null=True, upload_to='podcasts/'),
        ),
        migrations.AddIndex(
            model_name='dailypodcast',
            index=models.Index(fields=['status', '-created_at'], name='dailycast_d_status_58aedd_idx'),
        ),
    ]
