# Generated by Django 5.1.6 on 2025-12-11 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dailycast', '0003_studentlearninginsight_teachercontentconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedUserAnalytics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cached_analytics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('analytics_data', models.JSONField(help_text='Collected learning data snapshot')),
                ('reads', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Cached User Analytics',
                'verbose_name_plural': '📊 Cached User Analytics',
            },
        ),
        migrations.CreateModel(
            name='CacheStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, unique=True)),
                ('ai_insights_generated', models.IntegerField(default=0)),
                ('ai_insights_cached', models.IntegerField(default=0)),
                ('ai_insights_hits', models.IntegerField(default=0)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('ai_tokens_saved', models.IntegerField(default=0)),
                ('analytics_generated', models.IntegerField(default=0)),
                ('analytics_cached', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cache Statistics',
                'verbose_name_plural': '📈 Cache Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CachedAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, db_index=True, default='', help_text='Subject focus (empty = all subjects)', max_length=50)),
                ('engine', models.CharField(choices=[('gemini-2.0-flash-exp', '⚡ Gemini 2.0 Flash'), ('gemini-2.0-pro-exp', '✨ Gemini 2.0 Pro'), ('gemini-1.5-pro', '🔧 Gemini 1.5 Pro'), ('gpt-4o-mini', '⚡ GPT-4o Mini'), ('gpt-4o', '🎯 GPT-4o'), ('gpt-4-turbo', '🚀 GPT-4 Turbo')], default='gemini-2.0-flash-exp', max_length=50)),
                ('ai_insights', models.JSONField(help_text='Cached AI analysis (11 sections)')),
                ('tokens_used', models.IntegerField(default=0)),
                ('tokens_saved', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0, help_text='Times this cache was reused')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cached AI Insight',
                'verbose_name_plural': '💾 Cached AI Insights',
                'indexes': [models.Index(fields=['user', 'subject', 'engine'], name='dailycast_c_user_id_cfff1b_idx'), models.Index(fields=['expires_at'], name='dailycast_c_expires_025e2c_idx')],
                'unique_together': {('user', 'subject', 'engine')},
            },
        ),
    ]
