# Generated by Django 5.1.6 on 2025-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0003_fix_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypodcast',
            name='category',
            field=models.CharField(blank=True, help_text='Category/Subject of the request', max_length=100),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes/instructions'),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='profession',
            field=models.CharField(blank=True, help_text='Professional context', max_length=100),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full request payload including selected items'),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='topic',
            field=models.CharField(blank=True, help_text='Specific topic requested', max_length=255),
        ),
    ]
