# Generated by Django 5.1.6 on 2025-12-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0004_dailypodcast_category_dailypodcast_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypodcast',
            name='tts_provider',
            field=models.CharField(choices=[('openai', 'OpenAI TTS'), ('google', 'Google TTS (Standard)'), ('gemini', 'Google Journey (Gemini)'), ('google_chirp', 'Google AI Studio (Chirp)'), ('elevenlabs', 'ElevenLabs'), ('polly', 'Amazon Polly'), ('none', 'None')], default='polly', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable teacher content generation globally')),
                ('default_language', models.CharField(default='en', help_text='Default language for generation (en, ja, es, fr, de, etc)', max_length=12)),
                ('default_output_format', models.CharField(choices=[('text', 'Text Only'), ('audio', 'Audio Only'), ('both', 'Text & Audio')], default='both', help_text='Default output: text only, audio only, or both', max_length=10)),
                ('default_llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('template', 'Template')], default='template', help_text='Default LLM for script generation (template, OpenAI, Gemini)', max_length=20)),
                ('openai_model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model name (gpt-4, gpt-4o-mini, gpt-3.5-turbo, etc)', max_length=50)),
                ('gemini_model', models.CharField(default='gemini-2.0-pro-exp', help_text='Google Gemini model name', max_length=50)),
                ('default_tts_provider', models.CharField(choices=[('openai', 'OpenAI TTS'), ('google', 'Google TTS (Standard)'), ('gemini', 'Google Journey (Gemini)'), ('google_chirp', 'Google AI Studio (Chirp)'), ('elevenlabs', 'ElevenLabs'), ('polly', 'Amazon Polly'), ('none', 'None')], default='elevenlabs', help_text='Default TTS provider (elevenlabs, google, openai, polly)', max_length=20)),
                ('tts_fallback_chain', models.JSONField(blank=True, default=list, help_text='Fallback order: ["elevenlabs", "google", "openai"]')),
                ('tts_speaking_rate', models.FloatField(default=1.0, help_text='TTS speaking rate (0.5=slow, 1.0=normal, 1.5=fast)')),
                ('tts_pitch', models.FloatField(default=0.0, help_text='TTS pitch adjustment (-20.0 to +20.0)')),
                ('tts_volume_gain', models.FloatField(default=0.0, help_text='TTS volume gain in dB (-16.0 to +16.0)')),
                ('voice_map_json', models.JSONField(blank=True, default=dict, help_text='Map of language codes to voice IDs/names: {"en": "voice-id", "ja": "voice-id"}')),
                ('script_word_limit_normal', models.PositiveIntegerField(default=700, help_text='Target word count for normal scripts (for audio ~6-8 min)')),
                ('script_word_limit_short', models.PositiveIntegerField(default=300, help_text="Target word count for short scripts (when notes say 'short')")),
                ('script_include_questions', models.BooleanField(default=True, help_text='Include Q&A format in generated scripts')),
                ('num_questions_per_script', models.PositiveIntegerField(default=3, help_text='Number of questions to include in interactive scripts')),
                ('include_motivational_quote', models.BooleanField(default=True, help_text='Include motivational quote at the end')),
                ('prompt_system_role', models.TextField(default='You are a warm, enthusiastic, and engaging teacher.', help_text='System role/personality for LLM generation')),
                ('prompt_script_intro', models.TextField(default='Create a conversational teacher script for a student who is learning.', help_text='Introduction instruction for script generation')),
                ('prompt_tone_guide', models.TextField(default='Use natural pauses, show genuine emotion, speak with warmth like chatting with a friend.', help_text='Tone guidance for generated content')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours to wait between generations for regular users')),
                ('test_user_cooldown_enabled', models.BooleanField(default=False, help_text='Apply cooldown to test users (Alex)')),
                ('max_generations_per_day', models.PositiveIntegerField(default=0, help_text='Max generations per day per user (0=unlimited)')),
                ('cost_per_generation', models.DecimalField(decimal_places=2, default=0.5, help_text='Credit cost per generation (0=free)', max_digits=8)),
                ('enable_credit_system', models.BooleanField(default=False, help_text='Require users to spend credits for generation')),
                ('support_bilingual', models.BooleanField(default=True, help_text='Allow bilingual content (e.g. EN + JA)')),
                ('bilingual_default_pair', models.CharField(default='en_ja', help_text='Default bilingual pair format: "en_ja", "en_es", etc', max_length=20)),
                ('bilingual_audio_stitch', models.BooleanField(default=True, help_text='Stitch bilingual audio into single MP3 (vs separate files)')),
                ('verbose_logging', models.BooleanField(default=True, help_text='Log detailed info about each generation')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug output (use carefully in production)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Content Configuration',
                'verbose_name_plural': 'Teacher Content Configuration',
            },
        ),
    ]
