# Generated by Django 5.1.6 on 2025-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0004_cacheduseranalytics_cachestatistics_cachedaiinsight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachestatistics',
            options={'ordering': ['-date'], 'verbose_name': 'Cache Statistics', 'verbose_name_plural': '📈 Cache Statistics & API Costs'},
        ),
        migrations.AddField(
            model_name='cachestatistics',
            name='cost_saved_cents',
            field=models.IntegerField(default=0, help_text='Cost saved by caching in cents'),
        ),
        migrations.AddField(
            model_name='cachestatistics',
            name='cost_usd_cents',
            field=models.IntegerField(default=0, help_text='Total API cost in cents (e.g., 150 = $1.50)'),
        ),
    ]
