# Generated by Django 5.1.6 on 2025-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0005_alter_dailypodcast_tts_provider_teachercontentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypodcast',
            name='month_range',
            field=models.CharField(choices=[('current', 'Current Month'), ('last_3', 'Last 3 Months'), ('last_6', 'Last 6 Months'), ('last_12', 'Last Year (12 Months)'), ('all', 'All Time')], default='current', help_text='Time period for content included in podcast', max_length=20),
        ),
        migrations.AddField(
            model_name='dailypodcast',
            name='reply_size',
            field=models.CharField(choices=[('short', 'Short (2-3 minutes)'), ('medium', 'Medium (4-5 minutes)'), ('long', 'Long (6-8 minutes)'), ('detailed', 'Detailed (10+ minutes)')], default='medium', help_text='Duration/depth of podcast response', max_length=20),
        ),
    ]
