# Generated by Django 5.1.6 on 2025-12-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0006_dailypodcast_month_range_dailypodcast_reply_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Teachers, Students, Admins)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(help_text='Users in this category', related_name='podcast_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable content generation for this category')),
                ('default_language', models.CharField(default='en', help_text='Default language for this category', max_length=12)),
                ('default_output_format', models.CharField(choices=[('text', 'Text Only'), ('audio', 'Audio Only'), ('both', 'Text & Audio')], default='both', help_text='Default output format for this category', max_length=10)),
                ('default_llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('template', 'Template')], default='template', help_text='Default LLM provider for this category', max_length=20)),
                ('openai_model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model for this category', max_length=50)),
                ('default_tts_provider', models.CharField(choices=[('openai', 'OpenAI TTS'), ('google', 'Google TTS (Standard)'), ('gemini', 'Google Journey (Gemini)'), ('google_chirp', 'Google AI Studio (Chirp)'), ('elevenlabs', 'ElevenLabs'), ('polly', 'Amazon Polly'), ('none', 'None')], default='elevenlabs', help_text='Default TTS provider for this category', max_length=20)),
                ('tts_speaking_rate', models.FloatField(default=1.0, help_text='TTS speaking rate (0.5=slow, 1.0=normal, 1.5=fast)')),
                ('script_word_limit', models.PositiveIntegerField(default=700, help_text='Default word limit for scripts in this category')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours between generations (0=no limit)')),
                ('max_generations_per_day', models.PositiveIntegerField(default=5, help_text='Max generations per day (0=unlimited)')),
                ('cost_per_generation', models.DecimalField(decimal_places=2, default=0.5, help_text='Cost per podcast generation for this category', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='User category this config applies to', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='dailycast.usercategory')),
            ],
            options={
                'verbose_name': 'User Category Configuration',
                'verbose_name_plural': 'User Category Configurations',
            },
        ),
    ]
