# Generated by Django 5.1.6 on 2025-12-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycast', '0007_usercategory_usercategoryconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercontentconfig',
            options={'verbose_name': 'Global Podcast Defaults', 'verbose_name_plural': 'Global Podcast Defaults'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'ordering': ['name'], 'verbose_name': 'Student Group', 'verbose_name_plural': 'Student Groups'},
        ),
        migrations.AlterModelOptions(
            name='usercategoryconfig',
            options={'verbose_name': 'Category Override', 'verbose_name_plural': 'Category Overrides'},
        ),
        migrations.AddField(
            model_name='usercategoryconfig',
            name='claude_model',
            field=models.CharField(blank=True, default='claude-3-5-sonnet', help_text='Anthropic Claude model for this category', max_length=50),
        ),
        migrations.AddField(
            model_name='usercategoryconfig',
            name='gemini_model',
            field=models.CharField(blank=True, default='gemini-2.0-pro-exp', help_text='Google Gemini model for this category', max_length=50),
        ),
        migrations.AddField(
            model_name='usercategoryconfig',
            name='template_model',
            field=models.CharField(blank=True, default='template', help_text='Template model for this category (no AI)', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercategoryconfig',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='OpenAI model for this category', max_length=50),
        ),
    ]
