# Generated by Django 5.1.6 on 2025-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('lesson_clicked', 'Lesson Clicked'), ('quiz_started', 'Quiz Started'), ('quiz_submitted', 'Quiz Submitted'), ('quiz_answer_submitted', 'Quiz Answer Submitted')], max_length=50),
        ),
    ]
