# Generated by Django 5.1.6 on 2025-06-03 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Event (Analytics)', 'verbose_name_plural': 'Activity Events (Analytics)'},
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('lesson_clicked', 'Lesson Clicked'), ('quiz_started', 'Quiz Started'), ('quiz_submitted', 'Quiz Submitted'), ('quiz_completed', 'Quiz Completed'), ('quiz_answer_submitted', 'Quiz Answer Submitted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_activity_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
