# Generated by Django 5.1.6 on 2025-06-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_activityevent_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp of the last review/attempt for this item.', null=True)),
                ('next_review_at', models.DateTimeField(blank=True, db_index=True, help_text='Recommended next review timestamp.', null=True)),
                ('interval_days', models.FloatField(default=0.0, help_text='Current review interval in days.')),
                ('easiness_factor', models.FloatField(default=2.5, help_text='SM-2 Easiness Factor (typically starts at 2.5).')),
                ('repetitions', models.IntegerField(default=0, help_text='Number of times this item has been reviewed successfully in a row.')),
                ('current_retention_estimate', models.FloatField(default=1.0, help_text='Estimated current retention (0.0 to 1.0).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory Statistic',
                'verbose_name_plural': 'User Memory Statistics',
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='analytics_m_user_id_975f1c_idx'), models.Index(fields=['user', 'content_type', 'object_id'], name='analytics_m_user_id_757553_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
