# Generated by Django 5.1.6 on 2025-06-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_memorystat'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorystat',
            name='content_type',
            field=models.ForeignKey(help_text='The type of the learnable item (e.g., Question or Quiz).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='current_retention_estimate',
            field=models.FloatField(default=1.0, help_text='Estimated current retention (0.0 to 1.0), decays over time.'),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='easiness_factor',
            field=models.FloatField(default=2.5, help_text='SM-2 Easiness Factor (EF). Min 1.3.'),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='interval_days',
            field=models.FloatField(default=0.0, help_text='Current review interval in days (SM-2: I(n)).'),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='next_review_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the learnable item.'),
        ),
        migrations.AlterField(
            model_name='memorystat',
            name='repetitions',
            field=models.IntegerField(default=0, help_text='Number of times reviewed correctly in a row (SM-2: n).'),
        ),
    ]
