# Generated by Django 5.1.6 on 2025-11-20 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_quizattempt'),
        ('quizzes', '0006_quiz_published_at_quiz_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, help_text='UUID for a single continuous quiz attempt', null=True),
        ),
        migrations.CreateModel(
            name='QuizSessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID for this quiz attempt', unique=True)),
                ('total_questions', models.PositiveIntegerField(help_text='Set once on creation from quiz.questions.count()')),
                ('answered_count', models.PositiveIntegerField(default=0, help_text='Number of questions answered so far')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Number of correct answers so far')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(help_text='When first answer was logged')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When answered_count == total_questions', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progresses', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_session_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session Progress',
                'verbose_name_plural': 'Quiz Session Progresses',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id'], name='analytics_q_session_db6ce8_idx'), models.Index(fields=['user', 'quiz', 'status'], name='analytics_q_user_id_759e7c_idx')],
            },
        ),
    ]
