# Generated by Django 5.1.6 on 2025-11-10 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=191, unique=True, validators=[django.core.validators.RegexValidator('^\\S+$', 'Tags cannot contain spaces.')]),
        ),
    ]
