# Generated by Django 5.1.6 on 2025-05-11 08:23

import django.db.models.deletion
import quizzes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_delete_coursesnapshot'),
        ('lessons', '0011_alter_lesson_seo_title'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main explanation or content about the quiz.')),
                ('is_locked', models.BooleanField(default=False, help_text='Prevent editing after enrollment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('permalink', models.SlugField(blank=True, max_length=255, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.TextField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', models.URLField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='lessons.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_speech_to_text', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi', 'Multiple Select'), ('short', 'Short Answer'), ('dragdrop', 'Drag and Drop'), ('sort', 'Word Sorting')], default='mcq', help_text='Type of question (e.g., MCQ, Multiple Select, Drag & Drop)', max_length=20)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=quizzes.models.quiz_question_media_path)),
                ('question_image_alt', models.CharField(blank=True, max_length=150)),
                ('question_audio', models.FileField(blank=True, null=True, upload_to=quizzes.models.quiz_question_media_path)),
                ('option1', models.TextField(blank=True, null=True)),
                ('option1_image', models.ImageField(blank=True, null=True, upload_to=quizzes.models.option1_image_path)),
                ('option1_image_alt', models.CharField(blank=True, max_length=150)),
                ('option1_audio', models.FileField(blank=True, null=True, upload_to=quizzes.models.option1_audio_path)),
                ('option2', models.TextField(blank=True, null=True)),
                ('option2_image', models.ImageField(blank=True, null=True, upload_to=quizzes.models.option2_image_path)),
                ('option2_image_alt', models.CharField(blank=True, max_length=150)),
                ('option2_audio', models.FileField(blank=True, null=True, upload_to=quizzes.models.option2_audio_path)),
                ('option3', models.TextField(blank=True, null=True)),
                ('option3_image', models.ImageField(blank=True, null=True, upload_to=quizzes.models.option3_image_path)),
                ('option3_image_alt', models.CharField(blank=True, max_length=150)),
                ('option3_audio', models.FileField(blank=True, null=True, upload_to=quizzes.models.option3_audio_path)),
                ('option4', models.TextField(blank=True, null=True)),
                ('option4_image', models.ImageField(blank=True, null=True, upload_to=quizzes.models.option4_image_path)),
                ('option4_image_alt', models.CharField(blank=True, max_length=150)),
                ('option4_audio', models.FileField(blank=True, null=True, upload_to=quizzes.models.option4_audio_path)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, help_text='Correct option index (1-4) for MCQ.', null=True)),
                ('correct_options', models.JSONField(blank=True, help_text='List of correct option indices (e.g., [1, 3]) for Multi-Select, or solution structure for Sort/Drag.', null=True)),
                ('correct_answer', models.CharField(blank=True, help_text='Correct text answer for Short Answer.', max_length=255, null=True)),
                ('question_data', models.JSONField(blank=True, help_text='Data structure for Sort/Drag items/zones.', null=True)),
                ('hint1', models.TextField(blank=True)),
                ('hint2', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
        ),
    ]
