# Generated by Django 5.1.6 on 2025-02-28 05:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        ('subjects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main explanation or content about the quiz.')),
                ('question', django_ckeditor_5.fields.CKEditor5Field(help_text='Primary question for the quiz.')),
                ('option1', django_ckeditor_5.fields.CKEditor5Field()),
                ('option2', django_ckeditor_5.fields.CKEditor5Field()),
                ('option3', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('option4', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('correct_option', models.PositiveSmallIntegerField(help_text='Index of the correct option (1-4).')),
                ('hint1', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='First hint to help solve the quiz.')),
                ('hint2', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Second hint to help solve the quiz.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('permalink', models.SlugField(blank=True, max_length=255, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.TextField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', models.URLField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='lessons.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='subjects.subject')),
            ],
        ),
    ]
