# Generated by Django 5.1.6 on 2025-03-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('hint1', models.TextField(blank=True)),
                ('hint2', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='quizzes.quiz')),
            ],
        ),
    ]
