# Generated by Django 5.1.6 on 2025-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevent editing after enrollment.'),
        ),
    ]
