# Generated by Django 5.1.6 on 2025-05-31 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_difficulty_level'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Attach zero or more tags (auto-created if they don't exist).", related_name='quizzes', to='tags.tag'),
        ),
        migrations.CreateModel(
            name='FillBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(help_text="Sentence with '*' as blank placeholders, e.g. 'The quick * fox jumps *.'")),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank', to='quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='BlankWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('fill_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quizzes.fillblankquestion')),
            ],
        ),
        migrations.CreateModel(
            name='BlankSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(help_text='Zero-based index of the blank in the sentence')),
                ('correct_word', models.ForeignKey(help_text='Which word from the bank fills this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.blankword')),
                ('fill_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='quizzes.fillblankquestion')),
            ],
            options={
                'unique_together': {('fill_blank', 'slot_index')},
            },
        ),
    ]
