# Generated by Django 5.1.6 on 2025-03-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_coursesnapshot'),
        ('quizzes', '0003_quiz_is_locked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSnapshot',
        ),
    ]
