# Generated by Django 5.1.6 on 2025-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_tags_fillblankquestion_blankword_blanksolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='detected_location',
            field=models.CharField(blank=True, help_text='A location detected from the content, if any.', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Languages detected in the quiz content, e.g., ['en', 'ja']"),
        ),
    ]
