# Generated by Django 5.1.6 on 2025-04-27 07:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_delete_quizsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='hint1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='hint2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('option1', django_ckeditor_5.fields.CKEditor5Field()),
                ('option2', django_ckeditor_5.fields.CKEditor5Field()),
                ('option3', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('option4', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('hint1', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('hint2', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
        ),
    ]
