# Generated by Django 5.1.6 on 2025-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quiz_correct_option_remove_quiz_hint1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(help_text='Main explanation or content about the quiz.'),
        ),
    ]
