# Generated by Django 5.1.6 on 2025-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_question_hint1_alter_question_hint2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(blank=True, help_text='Main explanation or content about the quiz.'),
        ),
    ]
