# Generated by Django 5.1.6 on 2025-12-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_published_at_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avg_time_spent_ms',
            field=models.IntegerField(blank=True, help_text='Average time users spend on this question (milliseconds)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='computed_difficulty_score',
            field=models.FloatField(blank=True, help_text='AI-computed difficulty score (0-1000 scale)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='success_rate',
            field=models.FloatField(blank=True, help_text='Question success rate (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempt_count',
            field=models.IntegerField(default=0, help_text='Total number of quiz attempts (denormalized for sorting)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='avg_completion_time_seconds',
            field=models.FloatField(blank=True, help_text='Average time users spend completing this quiz', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='computed_difficulty_score',
            field=models.FloatField(blank=True, db_index=True, help_text='AI-computed difficulty score (0-1000 scale, matches user ability scale)', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='overall_success_rate',
            field=models.FloatField(blank=True, help_text='Overall success rate (0-100%) across all attempts', null=True),
        ),
    ]
