# Generated by Django 5.1.6 on 2025-05-05 06:09

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quiz_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_audio',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.option1_audio_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.option1_image_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_audio',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.option2_audio_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.option2_image_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_audio',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.option3_audio_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.option3_image_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_audio',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.option4_audio_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.option4_image_path),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.quiz_question_media_path),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.quiz_question_media_path),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
