# Generated by Django 5.1.6 on 2025-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_question_option1_audio_question_option1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_speech_to_text',
            field=models.BooleanField(default=False),
        ),
    ]
