# Generated by Django 5.1.6 on 2025-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_allow_speech_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_speech_to_text',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_options',
            field=models.JSONField(blank=True, help_text='For multiple-select questions, store list of correct option indices (e.g., [1, 3])', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_data',
            field=models.JSONField(blank=True, help_text='Flexible structure for drag/sort/multi options', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi', 'Multiple Select'), ('short', 'Short Answer'), ('dragdrop', 'Drag and Drop'), ('sort', 'Word Sorting')], default='mcq', help_text='Type of question (e.g., MCQ, Multiple Select, Drag & Drop)', max_length=20),
        ),
    ]
