# Generated by Django 5.1.6 on 2025-05-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_quiz_allow_speech_to_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='For short answer questions.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
