# Generated by Django 5.1.6 on 2025-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_speech_to_text',
            field=models.BooleanField(default=False),
        ),
    ]
