# Generated by Django 5.1.6 on 2025-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_question_allow_speech_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct text answer for Short Answer.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Correct option index (1-4) for MCQ.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_options',
            field=models.JSONField(blank=True, help_text='List of correct option indices (e.g., [1, 3]) for Multi-Select, or solution structure for Sort/Drag.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_data',
            field=models.JSONField(blank=True, help_text='Data structure for Sort/Drag items/zones.', null=True),
        ),
    ]
