# Generated by Django 5.1.6 on 2025-03-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('user_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.course'),
        ),
    ]
