# Generated by Django 5.1.6 on 2025-03-04 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0002_usermedia_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='media_category',
            field=models.CharField(blank=True, choices=[('course', 'Course'), ('post', 'Post'), ('quiz', 'Quiz'), ('lesson', 'Lesson')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
