# Generated by Django 5.1.6 on 2025-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoncompletion'),
        ('user_media', '0004_alter_usermedia_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lessons.lesson'),
        ),
    ]
