# Generated by Django 5.1.6 on 2025-03-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('user_media', '0005_usermedia_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post'),
        ),
    ]
