# Generated by Django 5.1.6 on 2025-03-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_course_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course_snapshot',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('course', 'Course'), ('quiz', 'Quiz'), ('lesson', 'Lesson')], default='course', max_length=20),
        ),
    ]
