# Generated by Django 5.1.6 on 2025-06-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_alter_enrollment_status_coursecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='shared_token',
            field=models.CharField(blank=True, help_text='One-time token for sharing this enrollment', max_length=64, null=True, unique=True),
        ),
    ]
