# Generated by Django 5.1.6 on 2025-06-20 08:13

import enrollment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_remove_enrollment_shared_token_collaborationsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareinvite',
            name='token',
            field=models.CharField(default=enrollment.models.generate_invite_token, editable=False, help_text='Unique token generated per invite', max_length=64, unique=True),
        ),
    ]
