# Generated by Django 5.1.6 on 2025-11-21 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('enrollment', '0008_alter_shareinvite_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collaborationsession',
            index=models.Index(fields=['enrollment', 'created_at'], name='enrollment__enrollm_69dfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'content_type', 'object_id', 'enrollment_type'], name='enrollment__user_id_1fb814_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionnote',
            index=models.Index(fields=['session', 'created_at'], name='enrollment__session_f0652d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionstroke',
            index=models.Index(fields=['session', 'created_at'], name='enrollment__session_a7dc84_idx'),
        ),
    ]
