# Generated by Django 5.1.6 on 2025-12-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_collaborationsession_enrollment__enrollm_69dfa6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the user started this course (enrollment date)', null=True),
        ),
    ]
