# Generated by Django 5.1.6 on 2025-11-24 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmagazine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermailmagazine',
            name='selected_recipients',
            field=models.ManyToManyField(blank=True, help_text='Select specific attendees to send this mail magazine to. Leave empty to send to all attendees.', related_name='received_mail_magazines', to=settings.AUTH_USER_MODEL),
        ),
    ]
