# Generated by Django 5.1.6 on 2025-11-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmagazine', '0002_teachermailmagazine_selected_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermailmagazine',
            name='times_sent',
            field=models.IntegerField(default=0, help_text='Number of times this magazine has been sent'),
        ),
    ]
