# Generated by Django 5.1.6 on 2025-11-25 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_selling_points_course_stripe_price_id_and_more'),
        ('mailmagazine', '0004_mailmagazineissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMagazineAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Automation rule name', max_length=200)),
                ('trigger_type', models.CharField(choices=[('enrollment', 'When User Enrolls in Course'), ('purchase', 'When User Purchases Product'), ('guide_attend', 'When User Attends as Guide'), ('course_complete', 'When User Completes Course')], max_length=50)),
                ('subject', models.CharField(help_text='Email subject (overrides template if set)', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Email body (overrides template if set)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this automation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailMagazineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=200)),
                ('template_type', models.CharField(choices=[('thank_attend', 'Thank You for Attending'), ('thank_purchase', 'Thank You for Purchase'), ('welcome_enroll', 'Welcome - Course Enrollment'), ('completion', 'Course Completion Congratulations'), ('custom', 'Custom Template')], default='custom', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('body', models.TextField(help_text='Email body content (HTML supported)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='mailmagazineissue',
            new_name='mailmagazin_magazin_5a971d_idx',
            old_name='mailmagazin_magazin_idx',
        ),
        migrations.AddField(
            model_name='mailmagazineautomation',
            name='specific_course',
            field=models.ForeignKey(blank=True, help_text='Only trigger for this specific course (leave empty for all courses)', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='mailmagazineautomation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailmagazinetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailmagazineautomation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='mailmagazine.mailmagazinetemplate'),
        ),
        migrations.AddField(
            model_name='teachermailmagazine',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional: Use a predefined template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazines', to='mailmagazine.mailmagazinetemplate'),
        ),
        migrations.AddIndex(
            model_name='mailmagazinetemplate',
            index=models.Index(fields=['created_by', 'template_type'], name='mailmagazin_created_487d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmagazineautomation',
            index=models.Index(fields=['teacher', 'trigger_type', 'is_active'], name='mailmagazin_teacher_e73cf5_idx'),
        ),
    ]
