# Generated by Django 5.1.6 on 2025-12-05 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_selling_points_course_stripe_price_id_and_more'),
        ('mailmagazine', '0005_mailmagazineautomation_mailmagazinetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., "Japanese Course A", "Premium Students")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the group', null=True)),
                ('is_dynamic', models.BooleanField(default=False, help_text='If True, automatically includes all course attendees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_course', models.ForeignKey(blank=True, help_text='For dynamic groups: link to a course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('members', models.ManyToManyField(blank=True, help_text='Students in this recipient group', related_name='recipient_groups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_recipient_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['teacher', '-updated_at'], name='mailmagazin_teacher_4dc4a0_idx')],
                'unique_together': {('teacher', 'name')},
            },
        ),
    ]
