# Generated by Django 5.1.6 on 2025-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
