# Generated by Django 5.1.6 on 2025-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_userpreference_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
