# Generated by Django 5.1.6 on 2025-07-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userpreference_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='timezone',
        ),
    ]
