# Generated by Django 5.1.6 on 2025-11-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_userpreference_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
