# Generated by Django 5.1.6 on 2025-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_fcmtoken_token_alter_fcmtoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
