# Generated by Django 5.1.6 on 2025-05-24 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_fcmtoken_unique_together_fcmtoken_device_id'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['user', '-last_seen']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
# migrations.RemoveField(
#     model_name='notification',
#     name='is_sent',
# ),
#        migrations.AddField(
 #           model_name='fcmlog',
  #          name='device_id',
   #         field=models.CharField(blank=True, help_text='Device ID associated with the token, if available.', max_length=255, null=True),
    #    ),
  #      migrations.AddField(
  #          model_name='fcmtoken',
  #          name='is_active',
  #          field=models.BooleanField(default=True, help_text='Token is active and can receive messages.'),
  #      ),
   #     migrations.AddField(
   #         model_name='fcmtoken',
   #         name='last_seen',
   ##         field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last time this token was seen or used.'),
    #    ),
     #   migrations.AddField(
     #       model_name='notification',
     #       name='is_sent_push',
     #       field=models.BooleanField(default=False, help_text='Tracks if a push notification was successfully sent for this.'),
     #   ),
        migrations.AlterField(
            model_name='fcmlog',
            name='action',
            field=models.CharField(choices=[('register', 'Register Token'), ('send_attempt', 'Send Attempt'), ('send_success', 'Send Success'), ('send_failure', 'Send Failure'), ('prune_token', 'Prune Token'), ('token_inactive', 'Mark Token Inactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fcmlog',
            name='detail',
            field=models.TextField(blank=True, help_text="E.g., error message, message ID, or 'Token created/updated'."),
        ),
        migrations.AlterField(
            model_name='fcmlog',
            name='success',
            field=models.BooleanField(blank=True, help_text='Indicates success of the action, if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='fcmlog',
            name='token',
            field=models.CharField(blank=True, help_text='The FCM token string involved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fcmlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_id',
            field=models.CharField(help_text="A unique ID for the user's device/browser instance.", max_length=255),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(help_text='Firebase Cloud Messaging registration token.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='guide_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_for_guide_request', to='social.guiderequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'device_id')},
        ),
    ]
