# Generated by Django 5.1.6 on 2025-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_fcmlog_options_alter_fcmtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmlog',
            name='token',
            field=models.TextField(blank=True, help_text='The FCM token string involved.'),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(help_text='Firebase Cloud Messaging registration token.'), # db_index=True was removed here
        ),
    ]
