# Generated by Django 5.1.6 on 2025-05-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_fcmlog_token_alter_fcmtoken_token'),
    ]


