# Generated by Django 5.1.6 on 2025-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_notification_is_sent'),
    ]

    operations = [

    ]
