# Generated by Django 5.1.6 on 2025-11-21 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_notification_is_sent_fcmlog_device_id_and_more'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fcmlog',
            index=models.Index(fields=['action', 'timestamp'], name='notificatio_action_388251_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'last_seen'], name='notificatio_user_id_c7fe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
    ]
