# Generated by Django 5.1.6 on 2025-03-09 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_testers',
            field=models.ManyToManyField(blank=True, related_name='allowed_test_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
