# Generated by Django 5.1.6 on 2025-03-09 23:58

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_allowed_testers_course_is_draft'),
        ('subjects', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=courses.models.course_cover_path)),
                ('course_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='courses.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
        ),
    ]
