# Generated by Django 5.1.6 on 2025-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesnapshot'),
        ('lessons', '0002_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesnapshot',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson'),
        ),
    ]
