# Generated by Django 5.1.6 on 2025-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursesnapshot_lessons'),
    ]


