# Generated by Django 5.1.6 on 2025-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursesnapshot_lessons'),
        ('quizzes', '0002_quizsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesnapshot',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quizzes.quizsnapshot'),
        ),
    ]
