# Generated by Django 5.1.6 on 2025-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursesnapshot_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevent further editing after the first user enrollment.'),
        ),
    ]
