# Generated by Django 5.1.6 on 2025-03-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_locked'),
        ('enrollment', '0003_remove_enrollment_course_snapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSnapshot',
        ),
    ]
