# Generated by Django 5.1.6 on 2025-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='The original URL path to redirect from', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='The destination URL path to redirect to', max_length=255)),
                ('permanent', models.BooleanField(default=True, help_text='True if the redirect is permanent (HTTP 301), else temporary (HTTP 302)')),
            ],
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='URL pattern or specific path for SEO settings', max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, help_text='SEO title for the page', max_length=70)),
                ('description', models.TextField(blank=True, help_text='SEO description for better search engine visibility', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content issues', null=True)),
            ],
        ),
    ]
