# Generated by Django 5.1.6 on 2025-03-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='path',
            field=models.CharField(help_text='URL pattern or specific path for SEO settings', max_length=191, unique=True),
        ),
    ]
