# Generated by Django 5.1.6 on 2025-12-05 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDifficultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the Quiz or Question')),
                ('computed_difficulty_score', models.FloatField(db_index=True, help_text='Computed difficulty score (0-1000 scale)')),
                ('avg_time_spent_seconds', models.FloatField(blank=True, help_text='Average time users spend on this content', null=True)),
                ('success_rate', models.FloatField(help_text='Overall correctness percentage (0-100%)')),
                ('attempt_count', models.IntegerField(default=0, help_text='Total number of attempts (for confidence weighting)')),
                ('difficulty_by_user_segment', models.JSONField(blank=True, default=dict, help_text="Dict: {'beginner': 650, 'intermediate': 480, 'advanced': 320}")),
                ('last_computed_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this difficulty score was last computed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Feature breakdown, model version, confidence intervals')),
                ('content_type', models.ForeignKey(help_text='Type of content (Quiz or Question)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Difficulty Profile',
                'verbose_name_plural': 'Content Difficulty Profiles',
                'ordering': ['-computed_difficulty_score'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='intelligenc_content_d5c648_idx'), models.Index(fields=['computed_difficulty_score', '-attempt_count'], name='intelligenc_compute_4d3d01_idx'), models.Index(fields=['last_computed_at'], name='intelligenc_last_co_73ac5b_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('match_score', models.FloatField(db_index=True, help_text='Overall match score (0-100, higher = better fit for this user)')),
                ('difficulty_gap', models.FloatField(help_text='Signed difference: content_difficulty - user_ability (optimal: -50 to +50)')),
                ('zpd_score', models.FloatField(blank=True, help_text='Zone of Proximal Development score (0-1, higher = optimal challenge level)', null=True)),
                ('preference_alignment_score', models.FloatField(blank=True, help_text='How well content matches user preferences (0-1, subject/tags/language)', null=True)),
                ('topic_similarity_score', models.FloatField(blank=True, help_text='Cosine similarity of content embeddings (0-1, if using semantic matching)', null=True)),
                ('recency_penalty', models.FloatField(default=0.0, help_text='Penalty for recently attempted content (0-1, higher = more recent)')),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this match score was computed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Breakdown of sub-scores, 'why' explanation for UI")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Score',
                'verbose_name_plural': 'Match Scores',
                'ordering': ['-match_score'],
                'indexes': [models.Index(fields=['user', '-match_score', 'computed_at'], name='intelligenc_user_id_7dd8ba_idx'), models.Index(fields=['content_type', 'object_id'], name='intelligenc_content_c2224d_idx'), models.Index(fields=['computed_at'], name='intelligenc_compute_650b32_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('personalized', 'Personalized'), ('review', 'Review Queue'), ('explore', 'Explore'), ('challenge', 'Challenge Mode')], help_text='Type of feed cached', max_length=50)),
                ('cached_quiz_ids', models.JSONField(default=list, help_text='Ordered list of Quiz IDs for this feed')),
                ('cached_metadata', models.JSONField(blank=True, default=dict, help_text="Pre-serialized 'why' explanations and scores per item")),
                ('cached_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this cache was last updated')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache should be invalidated')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache has been used (for analytics)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Cache',
                'verbose_name_plural': 'Recommendation Caches',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['user', 'feed_type', 'expires_at'], name='intelligenc_user_id_6c716c_idx'), models.Index(fields=['expires_at'], name='intelligenc_expires_0b06a0_idx')],
                'unique_together': {('user', 'feed_type')},
            },
        ),
        migrations.CreateModel(
            name='UserAbilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_ability_score', models.FloatField(db_index=True, default=400.0, help_text='Overall ability rating (0-1000 scale, higher = more advanced)')),
                ('ability_by_subject', models.JSONField(blank=True, default=dict, help_text='Dict mapping subject_id to ability score: {1: 450.0, 2: 520.0}')),
                ('ability_by_tag', models.JSONField(blank=True, default=dict, help_text="Dict mapping tag_name to ability score: {'algebra': 480.0}")),
                ('total_quizzes_attempted', models.IntegerField(default=0, help_text='Total number of quizzes attempted (for confidence weighting)')),
                ('total_correct_answers', models.IntegerField(default=0, help_text='Total correct answers across all quizzes')),
                ('recent_performance_trend', models.FloatField(default=0.0, help_text='30-day weighted performance trend (0-100%, higher = improving)')),
                ('global_rank', models.IntegerField(blank=True, db_index=True, help_text="User's rank among all users (1 = highest ability)", null=True)),
                ('percentile', models.FloatField(blank=True, help_text="User's percentile (0-100, higher = better than more users)", null=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this profile was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata: model_version, feature_importance, etc.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ability_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ability Profile',
                'verbose_name_plural': 'User Ability Profiles',
                'ordering': ['-overall_ability_score'],
                'indexes': [models.Index(fields=['overall_ability_score', '-last_computed_at'], name='intelligenc_overall_ca195c_idx'), models.Index(fields=['global_rank'], name='intelligenc_global__620bfc_idx')],
            },
        ),
    ]
