# Generated by Django 5.1.6 on 2025-05-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='growth_score',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='🌱 Growth Score: +1 per quiz, +2 per lesson, +3 per course completed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='impact_score',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='✨ Impact Score: +2 per quiz, +4 per lesson, +6 per course created; +1/+2/+3 when others complete'),
        ),
    ]
