# Generated by Django 5.1.6 on 2025-12-02 04:46

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_profile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for teacher introduction (will be embedded)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.showcase_image_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.showcase_image_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.showcase_image_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_about',
            field=models.TextField(blank=True, help_text='Detailed introduction, teaching philosophy, experience, credentials', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_tagline',
            field=models.CharField(blank=True, help_text="Short catchy tagline (e.g., 'Helping students master Japanese in 90 days')", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teaching_specialties',
            field=models.CharField(blank=True, help_text="Comma-separated specialties (e.g., 'JLPT N1, Business Japanese, Conversation')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website or portfolio', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel or intro video', null=True),
        ),
    ]
