# Generated by Django 5.1.6 on 2025-12-11 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0003_tag_description_tag_slug'),
        ('users', '0006_profile_intro_video_url_profile_linkedin_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ability_rank',
            field=models.IntegerField(blank=True, db_index=True, help_text="User's global rank among all users (1 = highest ability)", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_invite_teachers',
            field=models.BooleanField(default=False, help_text='Allow this teacher to invite others (admin permission required)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications (system notifications, guide requests, etc.)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ability_update',
            field=models.DateTimeField(blank=True, help_text='When ability scores were last computed', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_magazine_enabled',
            field=models.BooleanField(default=True, help_text='Receive mail magazine emails from teachers you follow'),
        ),
        migrations.AddField(
            model_name='profile',
            name='overall_ability_score',
            field=models.FloatField(blank=True, db_index=True, help_text='AI-computed overall ability score (0-1000 scale, higher = more advanced)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_1_caption',
            field=models.CharField(blank=True, help_text='Caption for showcase image 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_1_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for discoverability', related_name='showcase_1_profiles', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_2_caption',
            field=models.CharField(blank=True, help_text='Caption for showcase image 2', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_2_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for discoverability', related_name='showcase_2_profiles', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_3_caption',
            field=models.CharField(blank=True, help_text='Caption for showcase image 3', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showcase_image_3_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for discoverability', related_name='showcase_3_profiles', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese (日本語)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('zh', 'Chinese (中文)'), ('ko', 'Korean (한국어)')], default='en', help_text="User's native/preferred language for audio narration", max_length=12),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='report_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese (日本語)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('zh', 'Chinese (中文)'), ('ko', 'Korean (한국어)')], default='en', help_text='Language for daily study report audio (independent from native language)', max_length=12),
        ),
        migrations.CreateModel(
            name='GuideApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Why do you want to become a teacher on Zporta Academy?')),
                ('experience', models.TextField(blank=True, help_text='Teaching experience, credentials, certifications', null=True)),
                ('subjects_to_teach', models.CharField(help_text='Subjects/topics you plan to teach (comma-separated)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Which teacher invited/recommended you? (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_referrals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_guide_user_id_56777e_idx'), models.Index(fields=['status', 'created_at'], name='users_guide_status_5a5874_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(help_text='Email address of person being invited', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for invitation link', unique=True)),
                ('personal_message', models.TextField(blank=True, help_text='Personal message from inviter (optional)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiry date (30 days from creation)')),
                ('invitee', models.ForeignKey(blank=True, help_text='User account (if they registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='Teacher who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inviter', 'created_at'], name='users_teach_inviter_6f695e_idx'), models.Index(fields=['invitee_email'], name='users_teach_invitee_915267_idx'), models.Index(fields=['token'], name='users_teach_token_a20118_idx'), models.Index(fields=['status', 'expires_at'], name='users_teach_status_e585c8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('inviter', 'invitee_email'), name='unique_pending_invitation')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], db_index=True, max_length=10)),
                ('activity_type', models.CharField(choices=[('CORRECT_ANSWER', 'Correct Answer'), ('LESSON_COMPLETED', 'Lesson Completed'), ('COURSE_COMPLETED', 'Course Completed'), ('ENROLLMENT_FREE', 'Free Enrollment'), ('ENROLLMENT_PREMIUM', 'Premium Enrollment'), ('QUIZ_FIRST_ATTEMPT', 'First Quiz Attempt'), ('STANDALONE_LESSON', 'Standalone Lesson')], db_index=True, max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'role', 'created_at'], name='users_usera_user_id_5f8f9d_idx'), models.Index(fields=['user', 'activity_type', 'created_at'], name='users_usera_user_id_ab4acf_idx'), models.Index(fields=['created_at'], name='users_usera_created_828ca1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('session_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Most recent client heartbeat (activity ping)', null=True)),
                ('forced_closed', models.BooleanField(default=False, help_text='Marked true if auto-closed due to inactivity timeout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', 'login_at'], name='users_userl_user_id_333acc_idx')],
            },
        ),
    ]
