# Generated by Django 5.1.6 on 2025-12-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_intro_video_url_profile_linkedin_url_and_more'),
    ]

    operations = [
    ]
